[programs.localnet]
gem_bank = "BanKBNuJTREwxAUVwesmexkDJuMJ5atv9qBmdVAV5NiR"
gem_farm = "BgRpJNdfYdfLBFb1BZDQRK1bfqPqAotv3X88EUuC92BG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "C:/Users/Noris/Desktop/gem-farm/GEM6jvsYBTrQFkZAp3toE3m456n7MZeQRmXnR87LKhvE.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/mpl_token_metadata.so"

[[test.genesis]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"
program = "./tests/programs/mpl_token_auth_rules.so"
